// Copyright (c) 2026 Jeremy Ellis and contributors
//
// CodeBrix.LilyScheme is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

using System;
using System.Collections.Generic;
using System.Globalization;
using CodeBrix.LilyScheme.Values;

namespace CodeBrix.LilyScheme.Runtime;

/// <summary>
/// A Guile module: a namespace with its own bindings plus an ordered list of modules
/// whose exported bindings it can see. psyntax resolves every free identifier through
/// this structure, so the lookup order here is part of the expander's contract.
/// </summary>
public sealed class SchemeModule
{
    private static long _anonymousSerial;

    private readonly Dictionary<Symbol, Variable> _bindings = new Dictionary<Symbol, Variable>();
    private readonly List<SchemeModule> _uses = new List<SchemeModule>();
    private long _uniqueIdCounter;

    /// <summary>Initializes a module.</summary>
    /// <param name="name">The module name as a Scheme list, for example <c>(ice-9 match)</c>.</param>
    public SchemeModule(object name)
    {
        ModuleName = name ?? Nil.Instance;
    }

    /// <summary>Gets the module name as a Scheme list.</summary>
    public object ModuleName { get; private set; }

    /// <summary>
    /// Returns the module's name, giving an ANONYMOUS module a fresh one — and
    /// registering it — on first ask. This is Guile's own <c>module-name</c>
    /// behaviour (boot-9 gensyms a name and nested-defines the module), and psyntax
    /// depends on it: hygiene round-trips module identity BY NAME, so an imported
    /// macro used inside a module that cannot be named back simply does not resolve.
    /// That is exactly how LilyPond's anonymous parser scopes broke — every
    /// <c>define-music-function</c> read as a plain variable — and why the port's
    /// parser named its scopes as a workaround until this landed.
    /// </summary>
    /// <param name="registry">The registry the module joins when it gets its name;
    /// <see langword="null"/> returns the name as-is.</param>
    /// <returns>The module name, never <c>()</c> when a registry was given.</returns>
    public object EnsureName(ModuleRegistry registry)
    {
        if (ModuleName is Nil && registry != null)
        {
            long serial = System.Threading.Interlocked.Increment(ref _anonymousSerial);
            ModuleName = Pair.List(Symbol.Intern(
                "%anonymous-module-" + serial.ToString(CultureInfo.InvariantCulture)));
            registry.Register(this);
        }

        return ModuleName;
    }

    /// <summary>Gets the modules whose bindings are visible from here, in search order.</summary>
    public IReadOnlyList<SchemeModule> Uses => _uses;

    /// <summary>
    /// Gets or sets what KIND of module this is — Guile's <c>module-kind</c> field.
    /// <para><c>module</c> for an ordinary one, <c>interface</c> for the export view a
    /// <c>use-modules</c> builds, <c>directory</c> for a namespace node. Defaults to
    /// <c>module</c>, which is what boot-9's own constructor defaults it to.</para>
    /// </summary>
    public object Kind { get; set; } = Symbol.Intern("module");

    /// <summary>
    /// Gets or sets the table of this module's CHILD modules, keyed by their last name
    /// component — Guile's <c>module-submodules</c>.
    /// <para>A module named <c>(lily clip-region)</c> is a submodule of <c>(lily)</c>
    /// under the key <c>clip-region</c>. LilyPond's <c>session-save</c> snapshots the
    /// root's table and <c>session-terminate</c> puts it back, which is how one session's
    /// modules are kept from leaking into the next.</para>
    /// </summary>
    public Primitives.SchemeHashTable Submodules { get; set; }
        = new Primitives.SchemeHashTable(ReferenceComparer.Instance);

    /// <summary>Gets the module's own bindings.</summary>
    public IReadOnlyDictionary<Symbol, Variable> Bindings => _bindings;

    /// <summary>
    /// Gets the names this module EXPORTS — the ones a <c>define-public</c>, an
    /// <c>export</c> clause or a <c>#:export</c> keyword named.
    /// <para>
    /// A plain <c>define</c> is NOT in here, and that is the whole distinction: Guile's
    /// public interface holds exports only, so a helper defined privately inside a
    /// <c>(define-module (lily) …)</c> file is invisible to <c>module-public-interface</c>.
    /// LilyPond's manual is generated by walking that interface, so anything extra here
    /// becomes a documented procedure upstream does not document.
    /// </para>
    /// </summary>
    public ISet<Symbol> Exports { get; } = new HashSet<Symbol>();

    /// <summary>
    /// Gets or sets an explicitly installed public interface — Guile's
    /// <c>set-module-public-interface!</c>. When null, the interface is derived from
    /// <see cref="Exports"/> on demand.
    /// </summary>
    public SchemeModule PublicInterface { get; set; }

    /// <summary>Records that this module exports a name.</summary>
    /// <param name="name">The name to export.</param>
    public void Export(Symbol name)
    {
        if (name != null)
        {
            Exports.Add(name);
        }
    }

    /// <summary>
    /// Returns the module's public interface: a module holding exactly the exported
    /// names, bound to the SAME variables this module holds them in.
    /// <para>
    /// The variables are shared rather than copied — Guile's interface is built with
    /// <c>module-add!</c>, so a <c>set!</c> through either side is seen by both. Copying
    /// values instead would make the interface a stale snapshot of whatever had been
    /// defined by the time it was first asked for.
    /// </para>
    /// <para>
    /// Building it fresh on each call is deliberate: LilyPond loads more than fifty files
    /// INTO <c>(lily)</c> after the module is created, so an interface cached on first ask
    /// would answer for whatever had been exported at that moment.
    /// </para>
    /// </summary>
    /// <returns>The interface module.</returns>
    public SchemeModule Interface()
    {
        if (PublicInterface != null)
        {
            return PublicInterface;
        }

        SchemeModule iface = new SchemeModule(ModuleName)
        {
            Kind = Symbol.Intern("interface"),
        };

        foreach (Symbol name in Exports)
        {
            Variable variable = LookupLocal(name);
            if (variable != null)
            {
                iface.AddVariable(name, variable);
            }
        }

        return iface;
    }

    /// <summary>
    /// Gets the module this one is a LIVE public-interface view of, or null for an
    /// ordinary module. See <see cref="LiveInterfaceView"/>.
    /// </summary>
    public SchemeModule InterfaceBacking { get; private set; }

    /// <summary>
    /// Returns a live public-interface VIEW of this module: a module that answers
    /// exactly the names this module has exported — resolved at LOOKUP time, so an
    /// export added after the view was made still arrives, the way Guile's public
    /// interface object grows with its module. A re-exported name resolves through
    /// this module's own imports, which is where a re-export's variable lives.
    /// <para>
    /// The view has no use list of its own, so a lookup that reaches it stops there —
    /// the restriction that makes <c>Interpreter.NarrowModuleImports</c> give Guile's
    /// import-side privacy. It is what <c>use-modules</c> puts on the importer's use
    /// list when that switch is on.
    /// </para>
    /// </summary>
    /// <returns>The interface view.</returns>
    public SchemeModule LiveInterfaceView()
        => new SchemeModule(ModuleName)
        {
            Kind = Symbol.Intern("interface"),
            InterfaceBacking = this,
        };

    /// <summary>Adds a module to this one's import list. A second live interface view
    /// of a module already on the list is not added again.</summary>
    /// <param name="module">The module to import from.</param>
    public void AddUse(SchemeModule module)
    {
        if (module == null)
        {
            return;
        }

        foreach (SchemeModule existing in _uses)
        {
            if (ReferenceEquals(existing, module)
                || (module.InterfaceBacking != null
                    && ReferenceEquals(existing.InterfaceBacking, module.InterfaceBacking)))
            {
                return;
            }
        }

        _uses.Add(module);
    }

    /// <summary>
    /// Installs an EXISTING variable as this module's local binding for a name — Guile's
    /// <c>module-add!</c>, whose third argument is a variable object and not a value.
    /// <para>
    /// The difference from <see cref="Define"/> is the whole point of the operation:
    /// <c>Define</c> makes a variable of its own, so two modules that "share" a name by
    /// that route each get a private cell and a <c>set!</c> through one is invisible to
    /// the other. <c>module-add!</c> makes them share ONE cell. Guile code relies on
    /// that — LilyPond's <c>define-session-public</c> hands each parser scope the very
    /// variable that lives in <c>(lily)</c>, with the comment "we place the variable
    /// right into every parser module so that both set! and define will affect the
    /// original variable in the (lily) module".
    /// </para>
    /// </summary>
    /// <param name="name">The name to bind.</param>
    /// <param name="variable">The variable to install as the binding.</param>
    public void AddVariable(Symbol name, Variable variable)
    {
        if (name == null || variable == null)
        {
            return;
        }

        _bindings[name] = variable;
    }

    /// <summary>
    /// Removes this module's LOCAL binding for a name — Guile's <c>module-remove!</c>.
    /// <para>What it does not do is hide an imported binding of the same name: upstream
    /// removes the entry from the module's own obarray and nothing else, so a name the
    /// module was shadowing goes back to resolving through its imports.</para>
    /// </summary>
    /// <param name="name">The name to unbind locally.</param>
    /// <returns><see langword="true"/> when there was a local binding to remove.</returns>
    public bool Remove(Symbol name) => name != null && _bindings.Remove(name);

    /// <summary>
    /// Looks up a binding in this module only, ignoring imports. This is Guile's
    /// <c>module-local-variable</c>. A live interface view answers its backing
    /// module's EXPORTED names instead, resolved at call time.
    /// </summary>
    /// <param name="name">The name to look up.</param>
    /// <returns>The variable, or <see langword="null"/> when not bound locally.</returns>
    public Variable LookupLocal(Symbol name)
    {
        if (InterfaceBacking != null)
        {
            return InterfaceBacking.Exports.Contains(name) ? InterfaceBacking.Lookup(name) : null;
        }

        return _bindings.TryGetValue(name, out Variable variable) ? variable : null;
    }

    /// <summary>
    /// Looks up a binding here and then through imports, breadth-first, in IMPORT
    /// ORDER. This is Guile's <c>module-variable</c>.
    /// <para>
    /// DIVERGENCE, measured and kept: where two imports bind one name, the FIRST
    /// import wins here, while Guile's duplicate-binding handlers (default chain
    /// <c>(replace warn-override-core warn last)</c>) resolve toward the LAST module
    /// used and honor <c>#:replace</c>. A newest-first search was built and REVERTED
    /// the same day: it broke macro resolution across the LilyPond layer's module
    /// world (<c>make-engraver</c> read as an unbound variable — seven engraving
    /// tests red), because that world's scope chains were verified under this order.
    /// The practical cost is small — the known collision, <c>(srfi srfi-43)</c>'s
    /// <c>#:replace</c>'d trio, resolves to core bindings whose common arities now
    /// agree with the SRFI forms — but do not "fix" this order again without
    /// budgeting a full corpus sweep and suite run for it.
    /// </para>
    /// </summary>
    /// <param name="name">The name to look up.</param>
    /// <returns>The variable, or <see langword="null"/> when unbound everywhere.</returns>
    public Variable Lookup(Symbol name)
    {
        Variable local = LookupLocal(name);
        if (local != null)
        {
            return local;
        }

        HashSet<SchemeModule> seen = new HashSet<SchemeModule> { this };
        Queue<SchemeModule> pending = new Queue<SchemeModule>(_uses);
        while (pending.Count > 0)
        {
            SchemeModule module = pending.Dequeue();
            if (!seen.Add(module))
            {
                continue;
            }

            Variable found = module.LookupLocal(name);
            if (found != null)
            {
                return found;
            }

            foreach (SchemeModule next in module.Uses)
            {
                pending.Enqueue(next);
            }
        }

        return null;
    }

    /// <summary>Creates or updates a local binding.</summary>
    /// <param name="name">The name to bind.</param>
    /// <param name="value">The value to store.</param>
    /// <returns>The variable holding the value.</returns>
    public Variable Define(Symbol name, object value)
    {
        if (_bindings.TryGetValue(name, out Variable existing))
        {
            existing.SetValue(value);
            return existing;
        }

        Variable variable = new Variable(value);
        _bindings[name] = variable;
        return variable;
    }

    /// <summary>
    /// Returns the variable for a name, creating an unbound one locally when it does not
    /// exist. psyntax relies on this to reserve a slot before a definition is evaluated.
    /// </summary>
    /// <param name="name">The name to ensure.</param>
    /// <returns>The variable for that name.</returns>
    public Variable EnsureVariable(Symbol name)
    {
        Variable found = Lookup(name);
        if (found != null)
        {
            return found;
        }

        Variable variable = new Variable();
        _bindings[name] = variable;
        return variable;
    }

    /// <summary>Generates a module-scoped unique identifier, backing <c>module-generate-unique-id!</c>.</summary>
    /// <returns>A fresh integer, unique within this module.</returns>
    public long GenerateUniqueId() => ++_uniqueIdCounter;

    /// <summary>Returns the external representation.</summary>
    /// <returns>A description including the module name.</returns>
    public override string ToString() => "#<module " + Printer.Write(ModuleName) + ">";
}
